// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xarppibkokiuvugepvrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhcnBwaWJrb2tpdXZ1Z2VwdnJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjYxMTMsImV4cCI6MjA2OTA0MjExM30.kN_pPgsmy50NJHlOD_D8SFZ3gMkNcswYtqBZM_qqWOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});